# Generated by Django 3.2.5 on 2021-07-23 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('lifestyle &Culture', 'Lifestyles')], default='music', max_length=125)),
                ('story_image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('punch_line', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('story_content', models.TextField()),
                ('is_feature_post', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
