# Generated by Django 3.2.5 on 2021-07-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('lifestyle', 'Lifestyles')], default='music', max_length=125),
        ),
    ]
