# Generated by Django 3.2.5 on 2021-07-23 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story_posts', '0003_alter_storypost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypost',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
